name: Verify Repo Health Daily

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Lint-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Gives access to repository
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node version
        uses: actions/setup-node@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Generate frontend data
        run: node src/index.js

      - name: Install Frontend
        run: cd frontend && npm install

      - name: Build Vue
        run: cd frontend && npm run build

      - name: Deploy Vue Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
          user_name: 'OSS Sauce Bot'
          user_email: 'oss-sauce-bot@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
