name: Verify Repo Health Daily

on:
  schedule:
    - cron: '0 0 * * *'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Gives access to repository
      - name: Workflow access
        uses: actions/checkout@v2
      # Add node
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Generate frontend.json file
        run: node src/index.js

      - name: Install dependencies in frontend
        run: cd frontend && npm install

      - name: Build Vue
        run: cd frontend && npm run build

      - name: Deploy Vue Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
          user_name: 'OSS Sauce Bot'
          user_email: 'oss-sauce-bot@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
